{% set version = "2.1.5" %}
{% set build = 0 %}

package:
  name: pyfabm
  version: {{ version }}

source:
  url: https://github.com/fabm-model/fabm/releases/download/v{{ version }}/code.tar.gz
  sha256: 0565d5c6b79175f0917bfa93407ad1366ed3926b6bcb2be021e567f06c259bf8
  patches:
    #- fabm.patch
    #- ersem.patch
    #- ogs.patch

build:
  number: {{ build }}
  entry_points:
    - fabm_complete_yaml = pyfabm.utils.fabm_complete_yaml:main
    - fabm_configuration_gui = pyfabm.utils.fabm_configuration_gui:main
    - fabm_describe_model = pyfabm.utils.fabm_describe_model:main
    - fabm_evaluate = pyfabm.utils.fabm_evaluate:main
    - fabm_stress_test = pyfabm.utils.fabm_stress_test:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make                                   # [unix]
    - {{ compiler('fortran') }}              # [unix]
    - {{ stdlib("c") }}                      # [unix]
    - ninja                                  # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ stdlib("m2w64_c") }}                # [win]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - pyyaml
    #- m2w64-gcc-libgfortran                  # [win]

test:
  source_files:
    - testcases/fabm-gotm-npzd.yaml
  imports:
    - pyfabm
  requires:
    - netcdf4
    - pyside6
  commands:
    - fabm_complete_yaml -h
    - fabm_configuration_gui -h
    - fabm_describe_model -h
    - fabm_evaluate -h
    - fabm_stress_test -h
    - fabm_describe_model testcases/fabm-gotm-npzd.yaml

about:
  home: https://fabm.net/python
  summary: 'Python interface to the Framework for Aquatic Biogeochemical Models'
  description: |
    The Framework for Aquatic Biogeochemical Models (FABM) is a Fortran 2003
    programming framework for biogeochemical models of marine and freshwater
    systems.
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://fabm.net/wiki
  dev_url: https://fabm.net/code

extra:
  recipe-maintainers:
    - jornbr
