{% set version = "2.0.2" %}
{% set build = 0 %}

package:
  name: pyfabm
  version: {{ version }}

source:
  url: https://github.com/fabm-model/fabm/releases/download/v{{ version }}/code.tar.gz
  sha256: cc37f38f7e6e02b6361c13fec2f7e13ba6e053c03d20f280f8b4229101957226
  patches:
    #- fabm.patch
    - ersem.patch

build:
  number: {{ build }}
  entry_points:
    - fabm_complete_yaml = pyfabm.utils.fabm_complete_yaml:main
    - fabm_configuration_gui = pyfabm.utils.fabm_configuration_gui:main
    - fabm_describe_model = pyfabm.utils.fabm_describe_model:main
    - fabm_evaluate = pyfabm.utils.fabm_evaluate:main
    - fabm_stress_test = pyfabm.utils.fabm_stress_test:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('fortran') }}  # [unix]
    - make  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pyyaml
    - m2w64-gcc-libgfortran  # [win]

test:
  source_files:
    - testcases/fabm-gotm-npzd.yaml
  imports:
    - pyfabm
  requires:
    - netcdf4
    - pyqt
  commands:
    - fabm_complete_yaml -h
    - fabm_configuration_gui -h
    - fabm_describe_model -h
    - fabm_evaluate -h
    - fabm_stress_test -h
    - fabm_describe_model testcases/fabm-gotm-npzd.yaml

about:
  home: https://fabm.net/python
  summary: 'Python interface to the Framework for Aquatic Biogeochemical Models'
  description: |
    The Framework for Aquatic Biogeochemical Models (FABM) is a Fortran 2003
    programming framework for biogeochemical models of marine and freshwater
    systems.
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://fabm.net/wiki
  dev_url: https://fabm.net/code

extra:
  recipe-maintainers:
    - jornbr
